### ISSUE TITLE
xtheadfmv enable in rv32

### ISSUE THREAD

**Issue by RevySR** [cwt-lpi4a/linux-cwt-thead-lpi4a#1]
https://github.com/cwt-lpi4a/linux-cwt-thead-lpi4a/blob/c8c9241e33a4830b4b7ea6123c41256dd22e8d9c/2-add_TH1520_C910_CFLAGS_AFLAGS.patch#L75C32-L75C42

**Comment by RevySR** [comment]
https://github.com/T-head-Semi/thead-extension-spec/blob/master/xtheadfmv.adoc

**Comment by cwt** [comment]
Thanks, I will fix it as soon as I get back to home.
